# Generated by Django 3.0.3 on 2020-07-09 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0005_auto_20200709_0110'),
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clickevent',
            name='juli_url',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='shortener.JuliURL'),
        ),
    ]
